### ISSUE TITLE
Update event tracking

### ISSUE THREAD

**Issue by santiDotIO** [santi6291/monopoly-e-wallet#3]
- [x] make event wrapper white
- [x] use player color as a background around the player's name
- [x] fixed latest notification to the top of the app
